FROM python:2.7-alpine

ADD . /src
WORKDIR /src/tools/c7n_guardian
RUN python setup.py install
WORKDIR /src/tools/c7n_org
RUN python setup.py install
WORKDIR /src
RUN pip install -r requirements.txt
RUN python setup.py develop

VOLUME ["/var/log/cloud-custodian", "/etc/cloud-custodian"]

ENTRYPOINT ["/src/run.sh"]
